name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Verify CLI works
        run: ./dist/index.js --version

      - name: Run tests
        run: |
          # Installation test
          ./test/test-installation.sh

      - name: Performance benchmark
        run: npx tsx test/performance/benchmark.ts

      - name: Generate statusline sample
        run: |
          ./dist/index.js init --defaults --no-install
          ls -lah ./.claude/statusline.sh